site_name: Box
theme: null
theme_dir: 'docs-theme'
repo_url: https://github.com/box-builder/box
extra_css: [extra.css]
pages:
  - "Intro": "index.md"
  - "Usage": "usage.md"
  - "Download": "download.md"
  - "User Guide":
    - "Command-Line Options": "user-guide/cli.md"
    - "Verbs": "user-guide/verbs.md"
    - "Functions": "user-guide/functions.md"
